name: Deploy Docs with Qgoda

on:
  push:
    branches:
      - '**'

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # We want to own the output directory so that we can create a
      # file inside of it, see below.
      - name: Create _site directory.
        run: mkdir -p packages/docs/_site/e-invoice-eu

      # This is necessary because otherwise, the qgoda plug-ins are not found.
      - name: Run npm install
        run: npm install

      - name: Build with Qgoda
        uses: gflohr/qgoda-action@v1
        with:
          qgoda-version: latest-node
          qgoda-srcdir: packages/docs

      # See https://github.com/peaceiris/actions-gh-pages/issues/892
      - name: Create .exists
        run: touch packages/docs/_site/e-invoice-eu/.exists

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site/e-invoice-eu
